PUT http://localhost:8080/users/updateUserProfile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg1ODUyMTEsImlkIjo4LCJpc19zdXBlcnVzZXIiOnRydWUsImxvZ2luIjoieGExemVyIn0.rVgMTcTBjeoOs-crGrCYUnjjj7H7SU_pvEaGoWAYj-4
Content-Type: application/json

{
    "fat_percentage": 14.5,
    "muscle_percentage": 59.6
}