GET http://localhost:8080/users/showusers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg1NTMzMDYsImlkIjo5LCJpc19zdXBlcnVzZXIiOmZhbHNlLCJsb2dpbiI6InN1bmd1bmVpbGxvIn0.Nd4sgXYjGSwJYaQ-KK-WDWaZuypWNjRaDupTaT676Ig