GET http://localhost:8080/users/showusers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTc5Njc2NDUsImlkIjoxLCJpc19zdXBlcnVzZXIiOnRydWUsImxvZ2luIjoibTBncmFtbWVyU3VrYSJ9.ZHsZcyclUgKJekUaVial7bW4g_cV8jziHfbqpwCpjaA