GET http://localhost:8080/users/showusers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTc5NjQyODQsImlkIjo5LCJpc19zdXBlcnVzZXIiOnRydWUsImxvZ2luIjoic3VuZ3VuZWlsbG8ifQ.EkPj8pqA9-yLmA8-iowAlyXlKTDij-jBlueUrijeoEc