GET http://localhost:8080/trainers/showtrainers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg1ODIwNzYsImlkIjoxLCJpc19zdXBlcnVzZXIiOnRydWUsImxvZ2luIjoibTBncmFtbWVyU3VrYSJ9.BN03V4bX8s8-vooHpQWmAzui8VHRqepEztMl8pOjOOE